# Generated by Django 4.0.3 on 2022-04-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_supplier_remove_product_quantity_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='name1',
            new_name='supplier_name',
        ),
    ]
